### ISSUE TITLE
Plan Assignment Page Intermittent Error

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1015]
Both the plan jurisdiction assignment and the plan team assignment pages show an error message briefly while loading.  We need to ensure that the error message is only shown when a definite error has occurred

- [x] Fix for plan jurisdiction assignment
- [ ] Fix for plan team assignment

**Comment by p-netm** [comment]
my intuition tells me that; each of this views stops loading early, before the selectors actually populate the component with the fetched data.
something else tells me this behavior is because we have several `setLoading` calls all executing oblivious of where else they are getting called. so say if you have 2 promises that start at the same time, they will `setLoading` to true more or less at the same time; however when say promise A resolves 10 seconds earlier it will `setLoading` to false, irregardless of whether promise B has finished loading. 
The latter seems more probable.

**Comment by p-netm** [comment]
This error is not showing up for the plan Team assignment, at least not from my end.
