### ISSUE TITLE
Re assigning a team to a location it was assigned to before gives an error

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1174]
Re assigning a team to a location it was assigned to before gives an error:

`OpenSRPService create on organization/assignLocationsAndPlans failed, HTTP status 500`

### How to reproduce

- go to assign page
- select a plan
- drill down to a location
- assign a team
- save assignment
- then after some time 
- go to the same location
- un-assign the team u assigned to the location
- save
- then later come to the same location
- re assign the team
- saving the assignment fails with: `OpenSRPService create on organization/assignLocationsAndPlans failed, HTTP status 500`

**Comment by p-netm** [comment]
soo:
I can post an assignment for the first time: (this works)

```
[
  {
    fromDate: '2020-08-28T15:45:15+03:00',
    jurisdiction: 'ace82b81-1e64-425b-9264-315e9b00ef25',
    organization: '77b92036-8ffa-598e-92d8-c9c4c742b27a',
    plan: '1af11593-a731-5497-aa47-b3774acaa009',
    toDate: '2020-09-15T00:00:00+03:00',
  },
]
```

Then decide to revoke the assignment so I sent this:(this worked too)
```
[
  {
    fromDate: '2020-08-28T15:45:15+03:00',
    jurisdiction: 'ace82b81-1e64-425b-9264-315e9b00ef25',
    organization: '77b92036-8ffa-598e-92d8-c9c4c742b27a',
    plan: '1af11593-a731-5497-aa47-b3774acaa009',
    toDate: '2020-08-27T15:46:30+03:00',
  }
]
```

then I decide to assign the same team to the same plan, and same location, on the same day: this is where things go wrong.
```
[
  {
    fromDate: '2020-08-28T15:47:19+03:00',
    jurisdiction: 'ace82b81-1e64-425b-9264-315e9b00ef25',
    organization: '77b92036-8ffa-598e-92d8-c9c4c742b27a',
    plan: '1af11593-a731-5497-aa47-b3774acaa009',
    toDate: '2020-09-15T00:00:00+03:00',
  }
]
```

here are some notes from slack conversations around this:
> You should not create new assignments with fromDate  earlier than today unless you are editing an existing assignment

> There is a unique constraint on the following fields (organization_id, location_id, plan_id, from_date)

> you can't amend fromDate unless its a new assignment
> also you should not post date a new assignment with a backdated date

> for new assignments, I am using the plan effective start date if it is in the future, and now() if not.

Question: what should the 3 payload look like, so that we don't end up with a 500 error?

**Comment by moshthepitt** [comment]
@githengi thoughts on the above?

**Comment by p-netm** [comment]
from a conversation with Richard; things to do :
- for the second payload; we should not set the `toDate` to a day earlier than the day of unassignment.
- while doing this solves the problem here it does raise another for the web team:
it does not look like the unassignment takes into consideration the time portion of the `toDate`, as a result if you do an unassignment, technically the assignment will remain effective till the end of the day, that assignment json will be returned when `GET`ting existing assignments for that plan for the remaining part of that day.

**Comment by p-netm** [comment]
> from a conversation with Richard; things to do :
> 
>     * for the second payload; we should not set the `toDate` to a day earlier than the day of unassignment.
> 
>     * while doing this solves the problem here; it does raise another for the web team:
>       it does not look like the unassignment takes into consideration the time portion of the `toDate`, as a result if you do an unassignment, technically the assignment will remain effective till the end of the day, that assignment json will be returned when `GET`ting existing assignments for that plan for the remaining part of that day.

*Rechecking this*
