### ISSUE TITLE
Fix broken plan assignment page

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#1217]
After [this page loads](https://web.reveal-stage.smartregister.org/manualSelectJurisdictions/3ea2c755-e2b4-5bdd-88aa-c118e5ef44bc/f45b9380-c970-4dd1-8533-9e95ab12f128/f45b9380-c970-4dd1-8533-9e95ab12f128) and you click on Namibia, you get: https://sentry.onalabs.org/ona/reveal-web-stage/issues/82339/?query=is%3Aunresolved

**Comment by p-netm** [comment]
blocked by: https://github.com/OpenSRP/opensrp-server-web/issues/529.

the cause:
some Geojson are being returned with a `type`-field value of `feature` instead of `Feature` which is invalid, thus on this [line](https://github.com/onaio/reveal-frontend/blob/7160004edd5a533fe9733b86ad1f27febd1e82cc/src/containers/pages/AssigmentMapWrapper/index.tsx#L177), the geoJsonExtent helper runs into the error `feature is undefined` because; well it is expecting a valid GeoJson.

It also seems like after facing the error it mutates the data passed in as the argument,
 which led me on a wild goose chase.

**Comment by craigappl** [comment]
The root cause of this was the CGR integration where they returned the wrong geojson. We ran this once on reveal-stage and it caused these problems.

**Comment by moshthepitt** [comment]
Going to close this based on @craigappl's comment
