### ISSUE TITLE
How to handle reducing goal_comparator

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#122]
1. What is an example of a goal whose goal comparator value is `<` or `<=`?
2. How do you calculate progress towards its achievement?

**Comment by craigappl** [comment]
We do not have a clear use case for this. We should limit the comparator options to be "equal", "greater than" or "greater than or equal to" in the web UI. We can control this now because we are creating plans in Nifi or manually.

If this does come through, we should not calculate a target and possibly display an error in that card in the UI. Something like "Invalid Target"

**Comment by moshthepitt** [comment]
@craigappl @cKellyDesign right now the `goalPercentAchieved` function will always return a 0 for this.  Going to close this issue.  If it becomes a problem in the future we shall create new issues.
