### ISSUE TITLE
NTD MDA dashboards are not showing any data in Zambia production 

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1237]
Akros is currently doing another round of testing in Zambia production and none of the plans they have created are showing data in the dashboard. 

Specifically, they are testing right now with plan: "Dynamic-MDA 2020-09-02-blue" against the Zambia(vl 2020) hierarchy.

**Comment by moshthepitt** [comment]
Looks like data is now flowing in

![MDA-Reporting-Dynamic-MDA-2020-09-02-blue-Mutono-Zone-Reveal](https://user-images.githubusercontent.com/372073/92391188-df8e8f00-f124-11ea-8250-0a6211e381c8.png)


@isabelcshaw does this match what is expected?

**Comment by moshthepitt** [comment]
Fixed by https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/21, https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/22, https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/23, https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/24, and https://github.com/onaio/canopy/issues/1465
