### ISSUE TITLE
RVL-1134 - When sorting by last modified, the date and plan names change order but the dates and other columns do not 

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1253]
Login to web preview:
https://web.reveal-th-preview.smartregister.org/plans/list
Click on the sorting by last modified or status. Observe how the status column doesn't change
Observe how when sorting by last modified date the plan names change order but the dates and other columns do not

![image](https://user-images.githubusercontent.com/61143692/92382279-047b0600-f115-11ea-8f36-50e1c66562bb.png)

**Comment by p-netm** [comment]
This sems to arise due to the fact that both react and google translate are mutating the dom.
@samkanga you can confirm that the sorting works fine when not using translate.
cc @moshthepitt this might suggest a problem in terms of accessibility but I also think its more likely that its a limitation that arises due to how the technologies used, work., thoughts?

**Comment by moshthepitt** [comment]
@p-netm could you describe that some more?

**Comment by p-netm** [comment]
> @p-netm could you describe that some more?

I do not have all the nitty-gritty , but at a high level, using google translate breaks the sort functionality on the table. I think this is because both react and google translate work by mutating the DOM. i.e. google translate will change the table cells to be another node i.e `<font>`. I think this is what breaks the sorting functionality.
@moshthepitt

**Comment by samkanga** [comment]
@p-netm I can confirm that the sorting is working OK when I dont use google translate.

**Comment by moshthepitt** [comment]
Thanks @p-netm 

@samkanga I am going to shelve this issue for later because I believe for now the client has a viable workaround (i.e.not using Google translate)
