### ISSUE TITLE
Handle OpenSRP server responses with status 400 in the login/oauth2 flow gracefully

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#1302]
We are getting occasional 502 Bad Gateway errors on production environments after a user authenticates and the callback URL is being returned. This seems to be linked to a stopped pm2 service on the environments. Please add monitoring to identify when this happens so we can respond before a customer notices.

User's experience:
Reveal Namibia is getting 502 errors after authentication in Keycloak's trying to hit the oauth/callback URL
Visit web.reveal-na.smartregister.org
Click login button
Enter superset-user credentials
502 Bad Gateway Error
URL: https://web.reveal-na.smartregister.org/oauth/callback/OpenSRP/?state=opensrp&session_state=2ae1408a-2dfa-4bd4-baa4-5588a59e85ce&code=0768a123-d321-4abe-b8df-66e1e5de0768.2ae1408a-2dfa-4bd4-baa4-5588a59e85ce.afb20caa-c94b-440b-bb01-e1055ee6a955

Related to https://github.com/onaio/reveal-frontend/issues/1303

**Comment by ukanga** [comment]
The issue as we have identified had to do with the OpenSRP server responding with a 400 status code with the message "Cookie too large"
```
  caseless:
   Caseless {
     dict:
      { date: 'Mon, 21 Sep 2020 14:47:15 GMT',
        'content-type': 'text/html',
        'content-length': '226',
        connection: 'close',
        'set-cookie': [Array],
        server: 'nginx' } },
  body:
   '<html>\r\n<head><title>400 Request Header Or Cookie Too Large</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<center>Request Header Or Cookie Too Large</center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' }
undefined:1
<html>  caseless:
   Caseless {
     dict:
      { date: 'Mon, 21 Sep 2020 14:47:15 GMT',
        'content-type': 'text/html',
        'content-length': '226',
        connection: 'close',
        'set-cookie': [Array],
        server: 'nginx' } },
  body:
   '<html>\r\n<head><title>400 Request Header Or Cookie Too Large</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<center>Request Header Or Cookie Too Large</center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n' }
undefined:1
<html>
```
The resolution was to update the nginx configuration such that it could handle a larger sized header - we modified `large_client_header_buffers` to take `4 16k`.

We need the reveal-frontend to handle such cases and either report the error message to the user or report to Sentry or a similar service the error message from OpenSRP. Failing with a 502 is not really helpful in this case.

**Comment by ciremusyoka** [comment]
**Thailand local 502 error**
There is a JSON parse error cause by this [express line](https://github.com/onaio/express-server/blob/ae7f938d655b12ba90fb5195fd74a0b5537b3aa8/src/app/index.ts#L197). The line is expecting a string that can be serialized to JSON but receives the html document below when there is an invalid keycloak session on the browser.
`<!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</title><sty│
le type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76│
;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;│
font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;f│
ont-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} │
b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Ta│
homa,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {co│
lor:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HT│
TP Status 401 – Unauthorized</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Messa│
ge</b> Unable to authenticate using the Authorization header</p><p><b>Description</b> The reque│
st has not been applied because it lacks valid authentication credentials for the target resour│
ce.</p><hr class="line" /><h3>Apache Tomcat/9.0.26</h3></body></html>`

Adding a catch block will help.
Also we have to find a way of calling the react logout since the express logout only clears the express session.

**Comment by moshthepitt** [comment]
> Also we have to find a way of calling the react logout since the express logout only clears the express session.

We can probably just redirect to the react url that handles logging out and then React will do its thing.

**Comment by ciremusyoka** [comment]
Have tried this but it is only clearing the express session and not the keaycloak. Then on hitting the 'login with opensrp` it keeps redirecting back to login.
