### ISSUE TITLE
RVL-1197 - New families registered and data not displaying in Monitoring tab

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1304]
Plan: **Dynamic-FI 2020-09-21-VR Test II**
Monitoring tab: https://web.reveal-th-preview.smartregister.org/focus-investigation/map/8dd456a8-4725-5b3a-a025-cc5c10798d2a

1. Search for Plan in monitoring tab
2. Map does not display any data that was added on Android app

**Expected behaviour:** 
Structures from Android app is displayed: 4 residential structures, 1 larvae breeding site, 1 POAT, 1 mosquito collection point

See screen shot below:
![image](https://user-images.githubusercontent.com/5908630/93784781-0d4ff980-fc36-11ea-9fa2-7f11b3be5f9d.png)

**Comment by craigappl** [comment]
I reran all of the tasks and structures from serverVersion = 0. This seemed to have populated the geojson correctly in the tasks. Now, there's an issue with handling archived families in the targets. This portion of the ticket shows the updated items that need to be addressed.

We have 4 families registered, but the targets say 6. 
![image](https://user-images.githubusercontent.com/6067053/93830228-762e7600-fc24-11ea-9b9d-a4711ccfb5ee.png)

The underlying query for this is below:
```
SELECT task_identifier AS task_identifier,
       plan_id AS plan_id,
       jurisdiction_id AS jurisdiction_id,
       goal_id AS goal_id,
       geojson AS geojson
FROM
  (SELECT task_identifier,
          plan_id,
          jurisdiction_id,
          goal_id,
          jsonb_build_object('type', 'Feature', 'id', task_identifier, 'geometry', ST_AsGeoJSON(structure_geometry)::jsonb, 'properties', to_jsonb(row) - 'task_identifier' - 'structure_geometry') AS geojson
   FROM
     (SELECT task_identifier,
             plan_id,
             jurisdiction_id,
             task_status,
             task_business_status,
             task_focus,
             task_task_for,
             task_execution_start_date,
             task_execution_end_date,
             goal_id,
             action_code,
             jurisdiction_name,
             jurisdiction_parent_id,
             structure_id,
             structure_code,
             structure_name,
             structure_type,
             structure_geometry
      FROM task_structures_materialized_view) row) AS expr_qry
WHERE plan_id = 'a39d55a0-535b-5278-af83-615180de2a2d'
LIMIT 250;
```
That returns a total of 6 register family tasks. My suspicion is that 2 families were archived. 
Digging in, I will look at the first subquery to see the task status: This query confirms that there are 2 archived RACD_register_families tasks

I think what we need to do is remove the archived results from the underlying query here so that the numbers show up correctly.

**Comment by mberg** [comment]
Good sleuthing.

**Comment by craigappl** [comment]
We need to make the following changes.
1. (Done) Update this table to add WHERE task_status = 'Ready' OR task_status = 'Completed' on this slice https://superset.reveal-th-preview.smartregister.org/tablemodelview/edit/36
2. Update the targets_materialized_views to include a WHERE status = 'Ready' OR status = 'Completed' in https://github.com/OpenSRP/opensrp-reveal-datawarehouse/blob/master/3-reveal/migrations/4-FI/1-Thailand-2019/deploy/targets_materialized_view.psql#L78 and the associated test. This would ensure that the task count only counts the total number of Ready or Completed tasks, not archived or Cancelled.

**Comment by lincmba** [comment]
Created a PR [here](https://github.com/OpenSRP/opensrp-reveal-datawarehouse/pull/36) to address this. 

Both the targets_materialized_view and task_structures_materialized_view have been updated with these changes.
@craigappl @samkanga you may QA this.
