### ISSUE TITLE
Missing Plan for User on Thailand Local Production

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1398]
The user **vbdu_12.1.4-1** on Thailand Local Production cannot find [this](https://mhealth.ddc.moph.go.th/plans/update/3dd52eae-2d16-5d92-ac16-b35b5d90b503) plan in monitor tab.

**Comment by craigappl** [comment]
The root cause seems to be that the plan_jurisdiction table doesn't have this plan in it.

This returns no data:
```
SELECT *
FROM thailand_prod.plan_jurisdiction
WHERE plan_id = '3dd52eae-2d16-5d92-ac16-b35b5d90b503'
```
Then it shows up as follows in the superset slice as:
```
{
  "id": "011f2603-b41e-5dfd-b17b-1b87d5dea621",
  "plan_id": "3dd52eae-2d16-5d92-ac16-b35b5d90b503",
  "plan_title": "A1-ตลาดแบหอ-2020-11-04",
  "plan_name": "Dynamic-FI-2020-11-04",
  "plan_status": "active",
  "jurisdiction_id": null,
  "plan_fi_status": "A1",
  "plan_fi_reason": "Routine",
  "plan_date": "2020-11-04",
  "plan_effective_period_start": "2020-11-04",
  "plan_effective_period_end": "2020-11-09",
  "plan_intervention_type": "Dynamic-FI",
  "plan_version": "1",
  "jurisdiction_parent_id": null,
  "jurisdiction_name": null,
  "jurisdiction_geometry": null,
  "jurisdiction_depth": null,
  "jurisdiction_path": "null",
  "jurisdiction_name_path": "null",
  "jurisdiction_root_parent_id": null,
  "jurisdiction_root_parent_name": null
}
```
There are 3 plans in Thailand Local Production that are active and do not have a jurisdiction.

**Comment by Wambere** [comment]
The issue was that some records were trying to save data into the `plan_jurisdiction` table before the plan itself was saved in the `plans` table. I have updated the above 4 plans and moved the PG that saves the plan_jurisdiction to after the plan has been saved [here](https://nifimhealth.ddc.moph.go.th/nifi/?processGroupId=240b9c36-b60c-38b3-3e69-15c3341ef94d&componentIds=5d1c1c59-778e-34d1-46e1-973b7083d97a)
