### ISSUE TITLE
User raitest has no plans listed under the Manage Plans option

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1424]
- [ ] On Thailand preview environment, the user raitest is unable to see any plans while under the `Manage plans` option. The user however has plans available under the monitor tab.

**Comment by ciremusyoka** [comment]
@moshthepitt  the problem here is,  we are using the ids of the plans assigned to users to filter displayed plans from the list of all fetched plans, and currently we are fetching 2000 plans hence plans past the 2000 mark are not displayed.

**quick fix**
Increase the limit of plans we are fetching to lets say 3000 records (have tested this and it works). 
**solution**
Instead of getting Ids of user assigned plans and the filtering from all plans list, use the results directly as they are from the server. This sometimes will result to having two copies of same plan on the store but will solve the problem and we would have to worry when we start using server side pagination.

cc @samkanga

**Comment by moshthepitt** [comment]
> Instead of getting Ids of user assigned plans and the filtering from all plans list, use the results directly as they are from the server. This sometimes will result to having two copies of same plan on the store but will solve the problem and we would have to worry when we start using server side pagination.

@ciremusyoka not sure I understand this clearly.  What do you mean by "use the results directly as they are from the server"?

**Comment by ciremusyoka** [comment]
@moshthepitt when we do a fetch to get the plans assigned to a particular user, we only push the plan ids to the store and ignore the rest of the plans details. I meant instead of storing the ids only we store the whole of the plan to avoid the filtering

**Comment by moshthepitt** [comment]
@ciremusyoka 

Does that mean that:

- we will have a separate store that keeps records of a user's plans 
- we would then have a selector that filters the plans store using these plan ids (from the user-plan-id store)?

**Comment by ciremusyoka** [comment]
@moshthepitt 

- Yes will will have a separate store for storing user's plans. Not just the plan ids (like we are doing) but the plans.
- The selector will filter using user name
