### ISSUE TITLE
Add plan comment field for use when retiring a plan

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1475]
The BVBD team in Thailand would like to ensure that users provide additional details when retiring plans. This should be through a mandatory field that contains a drop down of reasons. This should be available when creating a plan or when editing a plan. Below are the allowable options and only one option can be selected at a time.

- กำหนดรายละเอียดแผนผิด (assigned wrong plan details)
- สร้างแผนซ้ำซ้อนจากที่มีอยู่ (Create duplicate plans from existing ones)
- ยกเลิกไม่ออกไปปฏิบัติงานแล้ว (Canceled, no longer going to work)
- กรอกที่อยู่ผู้ป่วยหรือที่อยู่แหล่งแพร่เชื้อผิดกลุ่มบ้าน (Enter the wrong address of the patient or source of infection)
- เป็นผู้ป่วยในกลุ่มบ้านเดียวกัน ณ สัปดาห์เดียวกัน (This is patient in the same sub-village and same week)
- ออกไปดำเนินการก่อนแผนปฏิบัติงานจะถูกสร้างขึ้น (We did an activity before the plan was created.)
- อื่นๆ (ระบุ) (Other (Please specify)) - User should be provided with a text field to fill out why they are retiring the plan.

Additional Considerations:
1. Potentially stored as an additional event - able to track state of event and reverse if need be: Preferred option for CHAI
2. Potentially create a new form if a user selects retire where the reference will be stored on the plan
3. Current plan data model doesn’t allow for this information to be stored will need to create a new event for the plan

**Comment by githengi** [comment]
For this ticket we should add editor to track the user who last edited the plan

When retiring the plan the event should be created that will capture the details on why the plan was retired

- The baseEntityId of the event to be plan identifier
- The eventType should be retire_plan
- The entityType should be Plandefinition
- The reason the plan was retired should be saved on the obs section of the event
- Any other details captured when retiring the plan now and in the future will be stored in the event obs
- ProviderId will be the user who has retired the plan
- LocationId can be jusridictionId of the plan, for plans with 1 jurisdiction, otherwise can be nulll
- Team and TeamId can be left as null

The plan shouldn't necessary have references to the events since the events will be tagging the event Type

**Comment by moshthepitt** [comment]
@githengi just for avoidance of doubt, could you post a sample JSON payload for this?

**Comment by githengi** [comment]
@moshthepitt below is the event schema

```
{
  "type": "Event",
  "baseEntityId": "{{plan_identifier}}",
  "locationId": "{{plan_location_identifier for plans with 1 location or empty otherwise}}",
  "eventDate": "{{ current date}}",
  "eventType": "Retire_Plan",
  "formSubmissionId": "{{uuid}}",
  "providerId": "{{logged in username}}",
  "obs": [
    {
      "set": [],
      "values": [
        "กำหนดรายละเอียดแผนผิด"
      ],
      "fieldCode": "retire_reason",
      "fieldType": "formsubmissionField",
      "parentCode": "",
      "fieldDataType": "text",
      "saveObsAsArray": false,
      "formSubmissionField": "retire_reason",
      "humanReadableValues": []
    }
  ],
  "entityType": "PlanDefinition",
  "details": {
    "planIdentifier": "{{plan_identifier}}"
  },
  "version": {{epoch timestamp}}
}
```

This can be posted to `/rest/event` enpoint

**Comment by moshthepitt** [comment]
Nice.  Thank you Sam.  @samkanga this one is now ready to be scheduled.

**Comment by samkanga** [comment]
@moshthepitt @ciremusyoka What is the estimated LoE for this ticket?

**Comment by ciremusyoka** [comment]
@samkanga @moshthepitt  this will take 2 days.
