### ISSUE TITLE
Could Not Load Points on Map Error on Thailand Monitoring Page

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1478]
Users cannot see the following 3 plan on the monitoring page for Thailand production.

- B2 ป่ามะกรูด (6508081101) 2021-01-26
- B1 ขยอง (3210110501) 2021-01-28
- A1 บ้านนา (1) (8203050304) 2021-02-01

A sample error can be accessed on the link [here](https://mhealth.ddc.moph.go.th/focus-investigation/view/ba93849d-9338-4f7d-a921-da25b36809df).

 
Below is a sample error that as it is being experienced:
![image](https://user-images.githubusercontent.com/5908630/106416445-748e7d80-6462-11eb-8360-1213d735dd3b.png)

**Comment by ciremusyoka** [comment]
This is happening because the jurisdictions don't have parents
`plan name:    B2-ป่ามะกรูด (6508081101)-2021-01-26`
`plan id:      2a8ed57a-ab0d-58e0-84da-642a75b2de39`
`jur id:       ba93849d-9338-4f7d-a921-da25b36809df`
`jur parent id: 5b8496aa-96ed-44e4-91ab-2255a3d1019f`

`plan name:    B1 ขยอง (3210110501) 2021-01-28`
`plan id:      5fa37f7e-6dc2-5943-bce9-2d8c72757883`
`jur id:       ed58aecd-7c68-4e76-8d00-938d0115650a`
`jur parent id: 2b8ef751-182f-4b7c-868f-18cb668bb3c7`

`plan name:    A1 บ้านนา (1) (8203050304) 2021-02-01`
`plan id:       f8269b90-ca46-5da2-95c6-c9e54de7a084`
`jur id:         ece5d31c-dd15-4050-a38a-11c97b2ac75e`
`jur_parent_id:  3672da62-13df-4329-82ae-ff59202f4c19`

**Comment by ciremusyoka** [comment]
The parents are not been loaded to the ware house because they don't have geometries.
parent ids `5b8496aa-96ed-44e4-91ab-2255a3d1019f,
2b8ef751-182f-4b7c-868f-18cb668bb3c7,
3672da62-13df-4329-82ae-ff59202f4c19`

**Comment by ciremusyoka** [comment]
Fixed by adding geometries with empty coordinates to the parent jurisdictions.
sample jurisdiction
```json
{
    "type": "Feature",
    "id": "d665dbd9-8449-47bd-b375-c34a1ab68310",
    "geometry": {
        "type": "Polygon",
        "coordinates": []
    },
    "properties": {
        "status": "Active",
        "parentId": "08bfcceb-59b2-456f-99ae-8a5263655c47",
        "name": "หมู่ที่ 5 (63030605)",
        "geographicLevel": 4,
        "version": 0,
        "OpenMRS_Id": "fe8952a0-b1ff-4947-9048-9dcc19be5239",
        "externalId": "63030605",
        "name_en": "Ban Dong Lan (63030605)"
    },
    "serverVersion": 1584673337315,
    "locationTags": [
        {
            "id": 3,
            "name": "Village"
        }
    ]
}
```

**Comment by samkanga** [comment]
This has been resolved and I will go ahead and close it.
