### ISSUE TITLE
Discrepancy between CSV data export for western province and dashboard for MACEPA IRS-Lite Western Live Plan- RVL 1456

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#1497]
There is no data for the user mcsik1  in the shared IRS lite data exports for the MACEPA IRS-Lite Western Live Plan,  the user was used by the team collecting data in Sikongo district in western province and data is populating on the dashboard.

 

There is data on the dashboard for the locations Sikongo. 
![image](https://user-images.githubusercontent.com/61143692/107939815-54011000-6f98-11eb-8e35-d09440a4aee0.png)
There is no data for the user mcsik1  on the CSV export who happened to be assigned to the Sikongo district.

![image](https://user-images.githubusercontent.com/61143692/107939845-61b69580-6f98-11eb-8e29-87efad824075.png)

**Comment by moshthepitt** [comment]
@Naima-Bashir some thoughts:

1. This data is not generated by the web app or Canopy, but on OpenSRP.  We may need to investigate if this user `mcsik1` has data in OpenSRP.  The results of that investigation would be very useful in figuring out what happened here.
2. Have we checked which provider_id appears in the data that we have?  Once that provider id is identified then the client would be in a better position to scope this issue out better.  i.e. there is not much we can do when the issue is reported as "there is no data for user `xyz`"

**Comment by moshthepitt** [comment]
This was resolved weeks ago
