### ISSUE TITLE
Audit routes and ensure users can't navigate to disabled routes

### ISSUE THREAD

**Issue by ciremusyoka** [onaio/reveal-frontend#1551]
Currently users are able to navigate to to disabled routes which should not be the case.

**Comment by moshthepitt** [comment]
@ciremusyoka can you show an example?

**Comment by ciremusyoka** [comment]
@moshthepitt for example `Planing Tool` page is not enabled on Thailand preview but if you enter the link manually you can still see data and access all other pages linked through it.
https://web.reveal-th-preview.smartregister.org/plans/planning

**Comment by moshthepitt** [comment]
@ciremusyoka okay I see.  However this isn't an access control feature, its just "hiding it".  We have two ways we could fix:

1. Tell the client/PM that its not meant for access control
2. Conditionally remove the Route entries for these hidden pages so that we get a 404-ish response when trying to access them
