### ISSUE TITLE
MDA Point Reporting: Child level views showing impossible data

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1555]
At the child level of the MDA Point reporting views, there are indicators about each individual child's drug administration. These should indicate if a child received drugs and which ones - or, if they opted out and why.

Right now, these views are showing "Yes" for indicators/columns 3-6, even though this is impossible from a data perspective. First, we know not all of those children have had an mda task completed, second, they can't have an mda task completed AND have refused the drug or opted out bc of a condition. And the ADR reported is an edge feature that will not have high usage and is its own form. Finally, these indicators don't match with the mda coverage counts on the higher levels of the same reports - many of them show 0 for number of drugs dispensed. This was originally reported in issue: [#1908](https://github.com/onaio/canopy/issues/1908)

Here is a screenshot of what this looks like:
![image](https://user-images.githubusercontent.com/5908630/115369169-8285ac00-a1d0-11eb-9a8c-edc6363dc9fa.png)

After discussion with @baokiddy and @gstuder-ona it is possible that this is happening because there are null values in the base view. @moshthepitt is it possible that we are showing "yes" as a response to "null"? @baokiddy null is the correct value for no information has yet been synced, correct?

Comment from @ciremusyoka : @moshthepitt on the web we have yes as long as the value is not equal 0. See [here](https://github.com/onaio/reveal-frontend/blob/f5211c508be3f95de81e4f824a8c3c3b3c2762b3/src/containers/pages/MDAPoint/ChildReports/index.tsx#L198-L202).

**Comment by moshthepitt** [comment]
@ciremusyoka @samkanga we should add the expected/acceptable outcome for this issue.  Not clear from the description.

**Comment by ciremusyoka** [comment]
On the web, [here](https://github.com/onaio/reveal-frontend/blob/f5211c508be3f95de81e4f824a8c3c3b3c2762b3/src/containers/pages/MDAPoint/ChildReports/index.tsx#L198-L202) is the code responsible for this bug.

@moshthepitt @haseemVD in case of `null` or `undefined`, we should display `NO` on the web.

**Comment by isabelcshaw** [comment]
@moshthepitt @haseemVD cc @samkanga @baokiddy @gstuder-ona 

The key goal here is to differentiate for the end user between whether there is data coming in for that child or if the data is in an empty or null state. 

**There are four states of information that should be shown to the user on the dashboard:** 
1. **Yes** - this means that we have received data that indicates that something did, in fact, occur. For example, we do have a record of a drug being dispensed, we do have a record that the drug was not given, adverse reaction (ADR) task completed, etc.  
2. **No** - this means that we have received data that indications that something did not happen. For example, we have a record that says that a drug was not dispensed or a SAC did not refuse. 
3. **No data** - my understanding is that this is what most of our current results are showing - that no data has come in for that child yet - basically "not yet." I know the views are pulling from multiple sources, so I'm not sure what the simplest consistent solution here is to make it clear to the end user that there is no data for that child. Ideally, this would show as either blank or the words "no data" 
4. **A value** - For three columns (name, national ID, PZQ tablets distributed) the result is a value of some kind instead of a yes, no, or not yet. These columns seem to be reporting correctly at the moment - blank when there is no data and showing the value when it is present. 

**Notes on the states above:** 
- For the "ADR Reported" field, the only two possible states are really "yes" or "no data" because adverse reactions are only registered if they happen. So, it would make the most sense to show a "No" anytime there is an absence of a "yes," but if it adds complexity, it is fine to just leave it blank 
- We should never have a case where you show either both "yes" or both "no" to "MMA drug administered" and 
"SACs Refused" - the child either was given the drug or refused the drug. But if a child has a completed MDA task, then there should be data (either "yes" or "no") showing up for all three fields: MMA drug administered, SACs Refused,  
SACs Sick/Pregnant/Contraindicated. 
- It is possible that a child won't have a national ID - it is not a required field 


**Here are example children and what I would expect the rows to look like:** 

**Child A** - _2 PZQ and 1 Alb tablet were dispensed to a child with no adverse reaction, enrolled in school, with a national ID_ 
Child's Name: Child A 
National ID: 09573927471
Enrolled in School: Yes 
MMA drug administered: Yes 
SACs Refused: No 
SACs Sick/Pregnant/Contraindicated: No 
ADR Reported:  
PZQ tablets distributed: 2 
Alb Tablets Distributed: Yes 

**Child B** - _1 PZQ and 0 Alb tablets were dispensed to a child with an adverse reaction, enrolled in school, with no national ID_ 
Child's Name: Child B 
National ID: 
Enrolled in School: Yes 
MMA drug administered: Yes 
SACs Refused: No 
SACs Sick/Pregnant/Contraindicated: No 
ADR Reported: Yes  
PZQ tablets distributed: 1 
Alb Tablets Distributed: No  

**Child C** - _child refused medication (0 PZQ and 0 Alb tablets were dispensed) a child with no adverse reaction, enrolled in school, with no national ID_ 
Child's Name: Child C 
National ID: 
Enrolled in School: Yes 
MMA drug administered: No
SACs Refused: Yes 
SACs Sick/Pregnant/Contraindicated: Yes
ADR Reported:   
PZQ tablets distributed: 0 
Alb Tablets Distributed: No

**Comment by ciremusyoka** [comment]
> We should never have a case where you show either both "yes" or both "no" to "MMA drug administered" and
"SACs Refused"

@moshthepitt @isabelcshaw  @haseemVD @samkanga my thinking here is we can  show "NO" on both columns. Meaning the drug has not been administered yet and also the student has not refused.

**Comment by samkanga** [comment]
@ciremusyoka going by @isabelcshaw explanation above, what you are describing appears to be a case of `No data`. `No` has been marked as to be used when a "negative" action happened such as drug was not dispensed.

**Comment by isabelcshaw** [comment]
@ciremusyoka the issue is that it really needs to be clear to the end user whether that child actually had an encounter with the system or not. So, for "MMA drug administered" - if we say "no" that means that they tried to give a drug to the kid and the kid did not take the medication. Which is very different from a campaign perspective from they just haven't gotten to them yet.

**Comment by haseemVD** [comment]
concluding above conversation,

- `null/undefined = No Data` (Not reached yet)
- `0 = No` (Declined)
- `some value = Yes` (Success)

@moshthepitt @ciremusyoka @isabelcshaw @samkanga

**Comment by samkanga** [comment]
@haseemVD the above appears correct. In addition take note of the instances under number 4 when we are expected to show the values. The section reads as follows: `A value - For three columns (name, national ID, PZQ tablets distributed) the result is a value of some kind instead of a yes, no, or not yet. These columns seem to be reporting correctly at the moment - blank when there is no data and showing the value when it is present.`

**Comment by ciremusyoka** [comment]
@baokiddy @gstuder-ona Please confirm which data should be used for `SACs Refused` and `SACs Sick/Pregnant/Contraindicated` columns, currently we are using `mmanodrugadminreason` for both.
cc @moshthepitt @samkanga @isabelcshaw @haseemVD 

Here is the data we are getting 
```
{
    "id": "19ef60de-16c3-50f7-80c3-940cbf1b1efe",
    "plan_id": "c05ad6b8-43a6-5ff8-a27d-dc7f2a635f49",
    "jurisdiction_id": "fa86faca-25df-44a3-8b8c-894649cac565",
    "jurisdiction_name": "Ngwane Practising",
    "jurisdiction_name_path": "[\"Eswatini\", \"Shiselweni\", \"Mbangweni\"]",
    "jurisdiction_path": "[\"bac41d87-b09d-4e76-be3b-3b6d07399891\", \"3ea27b09-96fe-4be5-b29f-490d63275ace\", \"fd5daf75-f1a1-412f-b1b2-d8d69927ad33\"]",
    "jurisdiction_parent_id": "fd5daf75-f1a1-412f-b1b2-d8d69927ad33",
    "is_virtual_jurisdiction": 0,
    "client_id": "980b0ce5-1493-4fd8-bb6f-8d9eb823e012",
    "client_location_id": "012f0601-b9bb-4d03-af59-0b59a6cebe31",
    "task_id": null,
    "task_location_id": "012f0601-b9bb-4d03-af59-0b59a6cebe31",
    "task_jurisdiction_id": null,
    "event_id": null,
    "event_type": null,
    "event_date": "NaT",
    "client_first_name": "Rachel",
    "client_last_name": "Rumbo",
    "client_base_entity_id": "8a520416-7f29-43b8-990f-6872bc8c7dda",
    "client_gender": "Female",
    "client_birthdate": "2010-05-11T00:00:00",
    "client_age": 10,
    "client_age_category": "6 - 10",
    "sactanationalid": null,
    "sactacurrenroll": null,
    "mmadrugadmin": null,
    "mmanodrugadminreason": null,
    "mmaadr": null,
    "mmaadrgrade": null,
    "mmapzqdosagegiven": null,
    "mmaalbgiven": null
}
```

**Comment by baokiddy** [comment]
@ciremusyoka Yes, you would be using `mmanodrugadminreason` to determine `SACs Refused` and `SACs Sick/Pregnant/Contraindicated`. These are the following responses that can be found in the `mmanodrugadminreason`  column:
- refused 
- sick
- contraindicated
- pregnant
- other

The first response would relate to  `SACs Refused` while the following 3 would relate to `SACs Sick/Pregnant/Contraindicated`. Not quite sure where "other" is mapped to. 
@gstuder-ona Please feel free to highlight anything I may have missed regarding the `mmanodrugadminreason`  column.

cc @moshthepitt @samkanga @isabelcshaw @haseemVD
