### ISSUE TITLE
Add Functionality to download Wards Metadata on Jurisdication Metadata CSV

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1572]
Wards on the MDA Lite setup are presented as structures. Hence, their respective names and IDs are not included when downloading the jurisdiction metadata csv. These details are required to guide users uploading population targets against the respective wards under the different sub-counties in Vihiga county. Presently the csv only provides details for the subcounties, county and country. See sample screenshot below.

![image](https://user-images.githubusercontent.com/5908630/116889803-a962ca00-ac35-11eb-9d6f-846202db09a4.png)

This ticket hopes to achieve the availability of the wards details on the jurisdiction metadata csv.

**Comment by moshthepitt** [comment]
@samkanga could you state again the expected outcomes of this?

**Comment by samkanga** [comment]
@moshthepitt: This tickets is aimed at building the function to retrieve wards and their identification details in the jurisdiction metadata csv for use in adding/uploading the population targets that are used on the End Fund dashboards.

**Comment by moshthepitt** [comment]
@samkanga I do not understand. Where is the ward data being extracted from?

To be clear, all the data in the jurisdiction metadata page is uploaded by the user.  So I am confused about how you envision this will work.

**Comment by ciremusyoka** [comment]
@moshthepitt For endfund wards are uploaded as structures and we currently only have the functionality of downloading jurisdictions.

**Comment by moshthepitt** [comment]
@ciremusyoka could you describe (technically) how what is proposed in this ticket would work?

**Comment by ciremusyoka** [comment]
@moshthepitt currently what we have for uploading and downloading (already uploaded) jurisdictions metadata is also working fine with structures. 
The missing part is the ability to download the CSV template containing structures since jurisdictions CSV template is created by getting the location hierarchy and processing it.
In order to download the structures CSV template we can have two options
1. For an hierarchy get all the lowest levels and request structures for those levels - This is already implemented on OpenSRP
2. Opensrp to add an endpoint such that if we send the country ID they give us back all the structures for that country.

On the web side.
My thought is we add another drop down above the one for selecting the country to download it's jurisdiction CSV template. The new drop down will have jurisdictions and structures options but with jurisdictions as default value.

**Comment by moshthepitt** [comment]
@ciremusyoka looks like what you want should be called "Structure Metadata".  In my view it should be a separate page on the web app that works mostly like "Jurisdiction Metadata" (might even share code!) but semantically it is different.

> Opensrp to add an endpoint such that if we send the country ID they give us back all the structures for that country.

Maybe explore this.  Would be interested to see what the endpoint returns.

**Comment by ciremusyoka** [comment]
> Opensrp to add an endpoint such that if we send the country ID they give us back all the structures for that country.

@Rkareko what is your take on ^
cc @samkanga

**Comment by Rkareko** [comment]
@ciremusyoka cc @samkanga We could add an endpoint to get structures for a given ancestor id which would either be a parent location or any level above this
