### ISSUE TITLE
SACs Sick/Pregnant/Contraindicated and ADR % indicators are not aggregating in reporting 

### ISSUE THREAD

**Issue by isabelcshaw** [onaio/reveal-frontend#1581]
The "SACs Sick/Pregnant/Contraindicated" indicator and the ADR % indicator are not aggregating upwards in the reporting views. 

If you look at plan [MDA-Point-2021-04-23](https://web.reveal-stage.smartregister.org/intervention/mda-point/report/a0913be4-7979-5a6d-8a2d-b9fdfd7b608a), you will see that there are 0 "SACs Sick/Pregnant/Contraindicated" and 0% ADR reported for all levels of the reporting views until you hit the school view. Then, there shows 3 "SACs Sick/Pregnant/Contraindicated" and 75% ADR reported. 

<img width="1243" alt="Screen Shot 2021-05-09 at 4 39 01 PM" src="https://user-images.githubusercontent.com/12836913/117590585-128a8780-b0e5-11eb-86e4-7e1fd5fb1a63.png">

<img width="1243" alt="Screen Shot 2021-05-09 at 4 36 57 PM" src="https://user-images.githubusercontent.com/12836913/117590520-c93a3800-b0e4-11eb-851e-f36ec2fcda72.png">

@baokiddy I know you just pushed a fix here - not sure if it wasn't included?

**Comment by baokiddy** [comment]
@isabelcshaw Looking into this since I was sure I pushed a fix for this.

@ciremusyoka what slice is the first table pointing to? I've included the correct image below for reference

<img width="1243" alt="Screen Shot 2021-05-09 at 4 39 01 PM" src="https://user-images.githubusercontent.com/12836913/117590585-128a8780-b0e5-11eb-86e4-7e1fd5fb1a63.png">

**Comment by ciremusyoka** [comment]
@baokiddy slice 574

**Comment by moshthepitt** [comment]
Done. Closing.  Please reopen if still an issue.
