### ISSUE TITLE
NTD School Level Data is Empty

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#1593]
MDA Point type Plans have been created and tasks completed against them and synced.  The reports are showing up in the MDA reporting view, but, consistently, the school level view is showing as empty. An example of such a plan is [here](https://web.reveal-stage.smartregister.org/intervention/mda-point/location-report/09a30098-75ae-5ee6-9942-69d811ed3b2a/f0de23e0-1e42-49e1-a60f-58d92040bbbb) and its screenshot is provided below. Please help investigate what is causing the `No rows found` error. What is it that the web app expects that is missing?

![image](https://user-images.githubusercontent.com/5908630/118464221-47ac6080-b709-11eb-8471-679e7e5167d1.png)

**Comment by haseemVD** [comment]
@samkanga API taking too long, after some time throws an error.
see screenshot attached
<img width="1440" alt="Screenshot 2021-05-17 at 6 09 43 PM" src="https://user-images.githubusercontent.com/68631902/118499622-8dd0e680-b740-11eb-8f70-80924c0b1953.png">

**Comment by samkanga** [comment]
@haseemVD confirming the issue with the API is now resolved.

**Comment by haseemVD** [comment]
> @haseemVD confirming the issue with the API is now resolved.

It is working now,
Thanks

**Comment by haseemVD** [comment]
@samkanga I've investigated and issue seems like in the response.
API is returning empty array because if which UI displays No rows found.
 Please find the attach screenshot, That might help 
 
<img width="962" alt="Screenshot 2021-05-17 at 7 13 02 PM" src="https://user-images.githubusercontent.com/68631902/118505273-b4dde700-b745-11eb-9511-8ccb697b3643.png">

API:
 `Request URL: https://superset.reveal-stage.smartregister.org/superset/slice_json/576?form_data={%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%22f0de23e0-1e42-49e1-a60f-58d92040cccc%22,%22operator%22:%22==%22,%22subject%22:%22jurisdiction_id%22},{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%2209a30098-75ae-5ee6-9942-69d811ed3b2a%22,%22operator%22:%22==%22,%22subject%22:%22plan_id%22}],%22row_limit%22:150}`
`Request Method: GET`

**Comment by samkanga** [comment]
@rkodev or @Rkareko who can help ascertain why the above API call is returning an empty array?

**Comment by samkanga** [comment]
Thank @haseemVD fr your input on this. This issue has been now resolved on the PR [here](https://github.com/onaio/data-solutions/pull/105). I will go ahead and close the ticket.
