### ISSUE TITLE
Thai-Preview Plans on the Action plan Report page not showing on some browsers

### ISSUE THREAD

**Issue by madrinekariuki** [onaio/reveal-frontend#1671]
Thai [preview ](https://web.reveal-th-preview.smartregister.org/)instance

Noted that plans are not showing on the Action reporting page on some browers. This was tested using Chrome and Also Mozilla.
On mozilla the plans were visible while on Chrome the plans were not visible and we are getting an error show below.(500 internal server error)

![image](https://user-images.githubusercontent.com/84722169/137481196-a3c96755-15b4-4b1e-a35a-5e85d05613bd.png)

**Comment by ciremusyoka** [comment]
This is an issue with superset failing to set cookie.

 https://supersetmhealth.ddc.moph.go.th/oauth-authorized/opensrp-preview request response error
 `this set-cookie didn't specify a samesite attribute and was default to samesite=lax and was blocked ....`


![Screenshot from 2021-10-15 15-44-57](https://user-images.githubusercontent.com/26719807/137489247-70accb43-3a72-4924-9c57-dae01cdc61cb.png)

This is probably happening because we are using different domains.

@lincmba @ukanga The superset  `samesite` config is set to none - `SESSION_COOKIE_SAMESITE = None `

**Comment by lincmba** [comment]
We are facing a `CORS error` and this is because of the difference in the domain names of the preview web and the production superset. A proper fix would be to change the domain name of the preview superset instance. 

Meanwhile the following solutions should be attempted from superset side:

- [ ] Have `CORS` origin urls defined
- [ ] Configure `SUPERSET_WEBSERVER_DOMAINS` to match `CORS` origin list
- [ ] Set `CORS` send_wildcard to `True`
- [ ] Set `CORS` allow_headers to match `CORS` origin list

**Comment by samkanga** [comment]
@lincmba I can follow-up with CHAI on the possibility of getting a preview superset subdomain on the same domain as the production superset. Would that be anything with the `*.ddc.moph.go.th` domain?

**Comment by lincmba** [comment]
Yes, that will work.

**Comment by ukanga** [comment]
@samkanga Please note, that this will require a subdomain for only the Reveal-Web piece i.e `web-preview.ddc.moph.go.th` since Superset is already in place `supersetmhealth.ddc.moph.go.th`. The new subdomain is primarily only for Reveal-Web.

**Comment by madrinekariuki** [comment]
@ciremusyoka 
please note that this is now affecting other browsers. see below screenshot when I tried to access the plans via Mozilla. 
![image](https://user-images.githubusercontent.com/84722169/141420056-2d00c2f8-ee8e-4343-a5af-d97fb8276f27.png)

**Comment by samkanga** [comment]
This has since been resolved.

**Comment by madrinekariuki** [comment]
This has also been tested on Thailand local instance and plans are showing well.

![image](https://user-images.githubusercontent.com/84722169/149166204-82412c5d-0e0e-4381-9bd1-92a19b79f7a0.png)
