### ISSUE TITLE
RACD plans generated via OpenSRP missing Patient details and Patient ID indicators.

### ISSUE THREAD

**Issue by madrinekariuki** [onaio/reveal-frontend#1676]
@ciremusyoka 

After RACD plan generation on thai preview was moved to OpenSRP as mentioned [here](https://github.com/opensrp/opensrp-server-web/issues/853). It has been noted that indicators on the plans for patient details and patient ID are missing.
The indicators keep loading but  nothing is eventually displayed.

steps:
login to the thai preview instance 
go to manage plans page
click on the plan
observe the indicators on the right side that are supposed to show the patient details keep loading and eventually do not show anything

screenshot
![image](https://user-images.githubusercontent.com/84722169/141320283-f8565dd1-29cf-4859-8864-ed52400feb5d.png)

**Comment by ciremusyoka** [comment]
@madrinekariuki  the event id (`opensrpEventId`) on the plans [JSON](https://github.com/opensrp/opensrp-server-web/issues/853#issuecomment-963971679) is not as expected,  `${opensrpCaseClassificationEventId}` instead of a valid UUID. 
Resulting request is send to `https://reveal-th-preview.smartregister.org/opensrp/rest/event/findById?id=${opensrpCaseClassificationEventId}`

**Comment by madrinekariuki** [comment]
This issue has now been fixed and  It is noted that the indicators are now showing and also on the Plans Json we now have a valid `opensrpCaseClassificationEventId` UUID

see below.
![image](https://user-images.githubusercontent.com/84722169/141758373-c05858e9-35d2-4634-820b-839a1fd6001d.png)
![image](https://user-images.githubusercontent.com/84722169/141758730-1ead6c45-91f1-40ca-8ab2-b928841ea7e9.png)
