### ISSUE TITLE
Scope Request: How to assign teams to plans?

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#306]
This ticket requests / tracks additional scoping for assigning teams to plans generated in the Reveal Webapp.

### Related Issues
OpenMRS Integration: https://github.com/OpenSRP/playbooks/issues/95 
UI / UX Requirements: https://github.com/onaio/reveal-frontend/issues/143
Client IRS Scoping (as of 12 July 2019): https://github.com/onaio/reveal-frontend/issues/192

### Wireframes 
W1. [First Load](https://marvelapp.com/b2iaahb/screen/53843108)
W2. [Drill-down - none assigned](https://marvelapp.com/b2iaahb/screen/53843109)
W3. [Team Assignment Popup](https://marvelapp.com/b2iaahb/screen/53843110)
W4. [Drill-down - team assigned](https://marvelapp.com/b2iaahb/screen/53843111)
W5. [All Jurisdictions assigned Teams](https://marvelapp.com/b2iaahb/screen/53843112)

### Questions
Q1. How do we access OpenMRS teams? (via OpenSRP or directly to OpenMRS?)
Q2. Are there plan-type specific requirements for assigning teams (FI vs IRS vs ?)
Q3. Which endpoints with what payloads are used to assign teams to tasks?
Q4. How do we know if tasks already have a team assigned?
Q5. Can we assign multiple Teams to a single Jurisdiction? (OA, FA, Spray Area)
Q6. Are there limitations on which Teams can be assigned to which Jurisdictions?
Q7. What comes after Team Assignment? (redirect to an overview? always stay on assign?)

cc - @mberg @craigappl @moshthepitt @githengi

**Comment by moshthepitt** [comment]
We should note that scoping/mockups for FI plans team assignments are entirely not there.

**Comment by cKellyDesign** [comment]
> We should note that scoping/mockups for FI plans team assignments are entirely not there.
cc @rowo

**Comment by craigappl** [comment]
@cKellyDesign , these are tough questions because we haven't thought about it at this level of detail yet. I'll do my best to answer:

> Q1. How do we access OpenMRS teams? (via OpenSRP or directly to OpenMRS?)
A1: I think we need to do this through the OpenSRP server as a passthrough so we don't have to deal with authenticating with OpenMRS from the web UI. My expectation is that the OpenSRP server would act as a proxy using some admin account to run all of the queries for teams.
> Q2. Are there plan-type specific requirements for assigning teams (FI vs IRS vs ?)
A2: Not that I know of
> Q3. Which endpoints with what payloads are used to assign teams to tasks?
A3: Tasks are assigned based on the plans. We don't assign teams to tasks right now. If a user has access to the plan, they have access to all teams. Each task as a "task owner" but we don't use that right now and set it to a generic NifiUser.
> Q4. How do we know if tasks already have a team assigned?
A4: This would be determined based on the plan as noted in A3.
> Q5. Can we assign multiple Teams to a single Jurisdiction? (OA, FA, Spray Area)
A5: I think the answer is No because we have a single entry in the OpenMRS location for team_id which doesn't accept comma separated values (as far as I know, please validate @githengi )
> Q6. Are there limitations on which Teams can be assigned to which Jurisdictions?
A6: Yes, this is based on the team assignment to the village within the team management module.
> Q7. What comes after Team Assignment? (redirect to an overview? always stay on assign?)
A7: @mberg what do you think?

I wrote up this document so you can see what's currently done in OpenMRS: https://smartregister.atlassian.net/wiki/spaces/REV/pages/1159921677/Team+Structure+and+User+Assingment

**Comment by mberg** [comment]
Q5 - Since we can just have a single team per jurisdiction, we'll need to just use OpenMRS to move people between teams for now.  This is something we'll need to improve later.

Q7 - After team assignment I'd keep it on the assign page as you may want to make another change.

**Comment by moshthepitt** [comment]
> we'll need to just use OpenMRS to move people between teams for now. This is something we'll need to improve later.

I do not think we should do this, [for these reasons](https://github.com/OpenSRP/playbooks/issues/95#issuecomment-515892180).  Additionally I don't think the LOE to use an OpenSRP proxy is so big that we need to make a compromise here.

**Comment by githengi** [comment]
Q5
> A5: I think the answer is No because we have a single entry in the OpenMRS location for team_id which doesn't accept comma separated values (as far as I know, please validate @githengi )

This can easily be extended to support a list of teams. But I think its better this is implemented when team module is moved to OpenSRP

**Comment by cKellyDesign** [comment]
Closing: Followup to this https://github.com/onaio/reveal-frontend/issues/143#issuecomment-526365840 will answer what we need to know.
