### ISSUE TITLE
Update Header Navigation

### ISSUE THREAD

**Issue by cKellyDesign** [onaio/reveal-frontend#432]
The structuring of the navigation needs to be updates:

- [x] Turn off `Reporting > Historic FI` (nest it in a new `env` variable)
- [x] Add link `Reporting > IRS` 
- [x] Rename `Planning > Manage Plans` to `All Plans`
- [x] Rename `Planning > IRS` to `IRS Plans`
- [x] Add link `Planning > Add New Plan`

cc @rowo @moshthepitt

**Comment by rowo** [comment]
@cKellyDesign Can you explain a bit on why the navigation changed from intervention focused to planning and reporting, or alternatively is there a log of the decision making I can look at?

**Comment by moshthepitt** [comment]
@rowo this is where the change was introduced https://github.com/onaio/reveal-frontend/pull/305

Basically I felt that the previous pages (like the focus investigation list that we had and still have) are not suitable when you are doing plans because they get data from Superset - and this data goes through an ETL process before it arrives there.  So it was common for you to create a plan but only see it 15min later or something.

The new "manage plans" page in contrast pulls directly from OpenSRP which is a much easier source of data when you are creating/updating plans.

**Comment by cKellyDesign** [comment]
@rowo I don't recall this being explicitly scoped, however Planning vs Reporting seems like a natural delineation to me as they are different activities / work flows / stages of the Plan Lifecycle. I suppose it does work both ways if we structure the Planning/Reporting the same under each intervention type, ideally we should get feedback from the client/users on this.

@mberg @craigappl - any input here?

**Comment by moshthepitt** [comment]
Fixed by #513 and #476
