### ISSUE TITLE
IRS reporting table view breaks when there is no data from Superset

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#491]
As in the site completely breaks with no recourse apart from a refresh.  We should handle this more gracefully.  Currently happening in Zambia production.

**Comment by cKellyDesign** [comment]
My suspicion is that our actionCreators that we're calling should be wrapped in a conditional to only save results to stores when there are results to save.

https://github.com/onaio/reveal-frontend/blob/master/src/containers/pages/IRS/JurisdictionsReport/index.tsx#L83

**Comment by moshthepitt** [comment]
@cKellyDesign I think we should do that regardless, but I feel that it is not the core problem - whether something goes into the Redux store or not shouldn't matter - ama?

**Comment by moshthepitt** [comment]
![ummm](https://user-images.githubusercontent.com/372073/66141674-bc9e5580-e60c-11e9-899c-b9c922ffcf3d.png)

So Zambia is currently doing this

**Comment by moshthepitt** [comment]
@cKellyDesign ^^

**Comment by cKellyDesign** [comment]
@moshthepitt Is there a level 0 Jurisdiction for `Zambia`?

**Comment by moshthepitt** [comment]
yes there is

**Comment by moshthepitt** [comment]
right now Zambia loads actually (coz we got some data synced) @cKellyDesign

**Comment by cKellyDesign** [comment]
@moshthepitt looks like it's working now in production
<img width="1186" alt="Screen Shot 2019-10-03 at 9 01 43 AM" src="https://user-images.githubusercontent.com/4141527/66143764-8b963480-e5bc-11e9-93a6-4ac2e21bb34f.png">

**Comment by moshthepitt** [comment]
yeah we got data in.  The screenshot above yours happens when there is no data for jurisdictions

**Comment by moshthepitt** [comment]
@cKellyDesign also, currently the map page is not showing on my end in Zambia

**Comment by cKellyDesign** [comment]
> currently the map page is not showing on my end in Zambia

@moshthepitt Seems there are no Jurisdicitons in the superset slice with this planId: https://superset.reveal-zm.smartregister.org/superset/slice_json/160?form_data={%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%229f1e0cfa-5313-49ff-af2c-f7dbf4fbdb9d%22,%22operator%22:%22==%22,%22subject%22:%22plan_id%22}],%22row_limit%22:1}

**Comment by moshthepitt** [comment]
@cKellyDesign this is 100% Superset behaving badly, the unfiltered slice https://superset.reveal-zm.smartregister.org/superset/slice_json/160 has all the jurisdictions with that plan id :(

**Comment by cKellyDesign** [comment]
@moshthepitt yeah actually I just realized, it's passing when in the table, seems the only reason this is failing is because the map is not calling it with the sorting parameter which is being used in the Table.

**Passing**
https://superset.reveal-zm.smartregister.org/superset/slice_json/160?form_data={%22order_by_cols%22:[%22[\%22jurisdiction_depth\%22,+true]%22],%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%229f1e0cfa-5313-49ff-af2c-f7dbf4fbdb9d%22,%22operator%22:%22==%22,%22subject%22:%22plan_id%22}],%22row_limit%22:3000}

**Failing**
https://superset.reveal-zm.smartregister.org/superset/slice_json/160?form_data={%22adhoc_filters%22:[{%22clause%22:%22WHERE%22,%22expressionType%22:%22SIMPLE%22,%22comparator%22:%229f1e0cfa-5313-49ff-af2c-f7dbf4fbdb9d%22,%22operator%22:%22==%22,%22subject%22:%22plan_id%22}],%22row_limit%22:1}

**Comment by moshthepitt** [comment]
@cKellyDesign I believe it is caused by weird caching behaviour in Superset where that particular query was cached with no results

**Comment by cKellyDesign** [comment]
ah yeah i was also wondering about the caching, how long does the cache persist?

**Comment by moshthepitt** [comment]
1200 sec right now

**Comment by cKellyDesign** [comment]
@moshthepitt is this still an issue?

**Comment by moshthepitt** [comment]
Not sure.  Lets close for now.
