### ISSUE TITLE
Assign Page breadcrumbs behaving badly

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#577]
Weird bug when you click on the breadcrumb link

![Oo](https://user-images.githubusercontent.com/372073/67893070-f492ad00-fb66-11e9-93c3-b4391ebe7b35.png)

**Comment by cKellyDesign** [comment]
@moshthepitt what are the repro steps? What are you clicking to get this?

**Comment by moshthepitt** [comment]
@cKellyDesign  Clicking repeatedly on `Tak` in the breadcrumbs - but noticed it on this plan only so far.

**Comment by cKellyDesign** [comment]
According to [the PlanDefinition for this plan](https://reveal-stage.smartregister.org/opensrp/rest/plans/68a8dbba-2986-58cb-9994-ef22285c094c) there is only a single jurisdiction in the plan, [which is `Tak` itself](https://reveal-stage.smartregister.org/opensrp/rest/location/5e37d232-d471-4ac1-b8a6-f5215a8aa117?is_jurisdiction=true&return_geometry=false) (which is invalid). I suspect this plan was never opened/saved in the jurisdiction selection page otherwise it would have resulted in all Tak descendant focus areas being selected.

### Proposed Solution
- [ ] Disallow the breadcrumbs to duplicate (ever) by checking the jurisditionIds of the existing breadcrumbs
- [ ] In the assign view, don't render parent jurisdictions (like Tak) as links unless there are descendant FAs in the saved in the actual planDefinition

This seems like a bit of an edge case so I'm resetting the priority level to medium.

**Comment by cKellyDesign** [comment]
I'm not sure if this is still happening, if not then let's close it.

**Comment by moshthepitt** [comment]
Closing this until we see it again
