### ISSUE TITLE
Investigate if filters on FI map page work ok

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#578]
This list seems odd to me

![Focus Investigation  A1 Akros_1 2019-09-05   Reveal Stage](https://user-images.githubusercontent.com/372073/67893557-d1b4c880-fb67-11e9-970d-f7c24484b5c5.png)

**Comment by moshthepitt** [comment]
When you go to the focus area page things are different:

![Focus Investigations in Akros_1   Reveal Stage](https://user-images.githubusercontent.com/372073/67893680-18a2be00-fb68-11e9-822c-3fef5394288f.png)

**Comment by cKellyDesign** [comment]
Not sure how the dropdown could be duplicating the same plan like this, will debug.

**Comment by cKellyDesign** [comment]
@moshthepitt after some digging it appears the issue here is the fact that the PlanDefinitions rendering in the dropdown were saved with the FI Reason `Case-triggered` while the focus area page is filtering plans for `Case Triggered`.

<img width="1086" alt="Screen Shot 2019-10-31 at 9 18 56 AM" src="https://user-images.githubusercontent.com/4141527/67923928-4f0c2780-fbc0-11e9-8275-73fb5ef7600e.png">

As long as new plans are being saved with the correct `Case Triggered` then this should be a non-issue.

**Comment by moshthepitt** [comment]
@cKellyDesign nice, thanks.  We can bring this to the attention of @craigappl, @ukanga  and @Wambere - so that they can investigate and clean the plans - and then close this issue.

**Comment by moshthepitt** [comment]
@cKellyDesign on second though should the select box do the same filtering as the focus area?

**Comment by cKellyDesign** [comment]
> should the select box do the same filtering as the focus area?

@moshthepitt I guess it could, it would just mean using `getPlansArray` twice, concatenating both lists, and sorting them by `plan_date`. This would at least make things consistent until the data is cleaned up.

**Comment by moshthepitt** [comment]
Fixed by https://github.com/onaio/reveal-frontend/pull/580
