### ISSUE TITLE
FI map breaks in Thailand production

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#637]
Reveal web version: 0.3.0

The map view in the monitor page does not load for Family Registration and Bednet Indicators (it loads for the other indicators)

![image (5)](https://user-images.githubusercontent.com/372073/73060786-aeb95c80-3ea9-11ea-9d4f-105e0a9fe82b.png)

**Comment by moshthepitt** [comment]
You can reproduce by trying to load this plan: `A1 Thailand test site BVBD 2 2020-01-09 RK release 3.1.2 การสอบสวน` on Thailand production

**Comment by moshthepitt** [comment]
It seems to work fine locally (but tested in English)

**Comment by moshthepitt** [comment]
@cKellyDesign note from Pierre:

> I can confirm that v0.2.9.2 works. To note - that version does not reload the map view, while the newer version does

(he means reload the map when you click on a goal)

**Comment by cKellyDesign** [comment]
@moshthepitt @craigappl Ok so there are a few things going on and a few things that are going to be very very difficult (if not impossible) to test in staging.

#### A. GA is forcing our components to re-mount
Our current implementation seems to be forcing our container components to unmount and remount, forcing every component on the page to unmount and remount. Ideally this should amount only to a performance issue as the components should have all the information they need to render correctly.

#### B. GisidaWrapper is not re-initializing the map after remounting 
This is the original issue raised above, and so far it is only in TH Prod v0.3.0. I have yet to reproduce this issue locally or see it live, and without reproducing the issue it will be very difficult to actually debug.

#### C. The reported plan has unexpected geometries (points) for structures
I'm not sure how related this is, but the geometries being returned from the structures slice in Superset is returning Points instead of Polygons, which the Mapbox map will not render because we are only rendering fill and line layers for structures. This should be a simple fix, but it will be hard to test locally b/c I don't know if there are any plan-jurisdictions in staging with points for structures.

### Proposed Next Steps
1. Add a circle layer to render structures that are points to resolve C. I don't know if this will effect B (and it won't effect A), but implementing this change would either rule it out or confirm it as the underlying issue for B. 
_Note: Unless we have a plan-jurisdiction with points as structures, we won't be able to test until we release to production_

2. Find or make a new plan in staging which actually reproduces B, then debug from there.
3. Update the GA functionality to only use the GA HOC component if the GA code is provided as `v0.3.1` (so we can avoid A while we...)
4. Deploy `v0.3.1` to TH Prod and disable GA so the client at least has translations (while we...)
5. Refactor the GA HOC component so it doesn't refresh our container components
6. Once persistent auth is implemented, come back to B and make sure the FI map fully initializes with goal indicators by refreshing the page and debugging from there.

**Comment by moshthepitt** [comment]
@cKellyDesign good sleuthing - thank you!

> Add a circle layer to render structures that are points to resolve C. I don't know if this will effect B (and it won't effect A), but implementing this change would either rule it out or confirm it as the underlying issue for B.

For this if we can do it like we did it for IRS maps, it would be super cool.  This should fix C above.

> Update the GA functionality to only use the GA HOC component if the GA code is provided as v0.3.1 (so we can avoid A while we...)

Lets get an issue up for this.

**Comment by cKellyDesign** [comment]
> For this if we can do it like we did it for IRS maps, it would be super cool.

@moshthepitt do you mean how the IRS container builds the layers and hands those to the GisidaWrapper? Agreed we should, it would mean pushing the FI business logic out of the wrapper and into the FI container. It might be easier to do refactor this all at once rather than doing it piecemeal.

**Comment by moshthepitt** [comment]
> @moshthepitt do you mean how the IRS container builds the layers and hands those to the GisidaWrapper? Agreed we should, it would mean pushing the FI business logic out of the wrapper and into the FI container. It might be easier to do refactor this all at once rather than doing it piecemeal.

Yes that's exactly what I meant :-)

**Comment by cKellyDesign** [comment]
Great! I'm going to add some filtering and a layer here which can be shifted with the rest as a part fo the greater refactor effort (I think there's a ticket for the greater effort).

**Comment by moshthepitt** [comment]
It seems that this was fixed in the v0.4.2 release candidates.

**Comment by moshthepitt** [comment]
Was superseded by https://github.com/onaio/reveal-frontend/pull/917
