### ISSUE TITLE
RVL-838 - Show Index Case details on Manage Plans screen for reactive intervention

### ISSUE THREAD

**Issue by moshthepitt** [onaio/reveal-frontend#647]
This new information needs to be shown on Manage Plans page for FI plans:

### Change to be made:

1. Show Case Number and sdd a collapsible section labelled “Case Details” under “Case Number” with fields  (need to confirm if all of these fields pulling from BIOPHICS into Reveal)
    - Case Information
        - Case Classification
        - Date of Diagnosis
        - Species
        - Notification Date
        - Investigation Date
        - House Number
        - Patient Name
        - Surname
        - Age
    - Foci Information
        - Foci of Residence
            - ID
            - Classification
            - Name
        - Foci of Infection (Blank if same as above)
            - ID
            - Classification
            - Name

### Business Logic:

- One index case should return
- All fields are read only
- The section should be shown by default with the ability to collapse
- The section only displays if the Focus Investigation Reason = Case Triggered

More info: https://smartregister.atlassian.net/browse/RVL-838

**Comment by moshthepitt** [comment]
@craigappl @samkanga I have some concerns about this issue:

1. The information that needs to be displayed for a plan does not seem to "conceptually" belong on the manage plans page.
    - The intention of "manage plans" is to perform CRUD oparions on plans and not reports for plans per se.
    - I feel that this information should be made available elsewhere in the web UI and perhaps a link can be put in the mange plans section.  
   - In my view we need to re-scope how reporting for FI should work so that we have a better understanding of where such information belongs.
   - I feel that we should not agree to put this information here or that other information elsewhere in the web UI without a solid plan
2. This needs a significant amount of work both in the data ware house and in the web UI
   - all of the information that needs to be displayed needs to be extracted from event info and made available to the web app
   - the web UI needs to be built
   - do we have mockups for this?
3. In my mental map, the manage plans deals only with the OpenSRP APIs for plans (and not with things that come from the data warehouse via Superset - that is why this page is nice and fast).  My mental map may need to change, but we need to discuss and justify any changes

**Comment by craigappl** [comment]
@moshthepitt (FYI @samkanga )

These case event details are created in the BIOPHICS system when a plan is generated. We have Nifi processes that autogenerate the plan and post an event to the reveal server. At this time, we auto-generate "active" plans at this time and they want this feature to auto-generate "draft" plans. The customer needs to view these case details so they can make a decision on whether to activate the plan or not.

I don't see this as a report, I see this as another call to the OpenSRP endpoint to return the event details that triggered this plan and provide that information so that the user can make an informed decision and perform an "update" on the plan that was auto-generated.

Here's the workflow that's currently built:
- Nifi picks up a new case from BIOPHICS
- Nifi creates an event and POSTs it to Reveal
- Nifi creates an active plan and POSTs it to Reveal.

Here's the updated workflow:
- Nifi picks up a new case from BIOPHICS
- Nifi creates an event and POSTs it to Reveal
- Nifi creates a draft plan and POSTs it to Reveal.
- A user logs into the web UI to view draft plans
- A user clicks the drop-down to see case details
- The user changes the status to active
- The user saves the plan
- The Web UI PUTs the plan to the Reveal server

Here's some background on what's available
- Each plan has an OpenSRP event Id in the useContext field {"code":"opensrpEventId","valueCodableConcept":"NNNNN"}
- The OpenSRP server has a URL endpoint to access the event: https://reveal-th.smartregister.org/opensrp/rest/event/findById?id=
- The event has a fixed structure that we can count on and parse as JSON to present to the user

Here's the flow that we need to add to the UI:
- When a user opens the plan, perform logic to see if this is a reactive plan.
- If it's a reactive plan, verify that the usecontext includes a code opensrpEventId If so, perform an Asynchronous call to the events endpoint (put a loading spinner in place of the case details box)
- Once returned, render the component in the UI based on the spec that's in the ticket.

**Comment by p-netm** [comment]
@samkanga @craigappl cc @moshthepitt 
Need some help knowing how do the above fields map to the event object we get from opensrp?.
I have prefilled some with what i could deduce, but i might be wrong.

**Case Information**
Case Classification : `event.detail.case_classification`
Date of Diagnosis: `event.eventDate`
Species: `event.details.species`
Notification Date: `???`
Investigation Date: `event.details.investigtion_date`
House Number: `event.details.house_number`
Patient Name: `event.details.firstName` + `event.details.surname`
Surname: `event.details.surname`
Age: `event.details.age`
**Foci Information**
_Foci of Residence_
    ID: `???`
    Classification: `???`
    Name: `???`
_Foci of Infection (Blank if same as above)_
    ID: `???`
    Classification: `???`
    Name: `???`


Here is a sample event:

```
{
    "type": "Event",
    "dateCreated": 1580093363439,
    "serverVersion": 1580093363439,
    "identifiers": {},
    "baseEntityId": "8868450-efbaf9795d2a",
    "locationId": "88684506-605d-fbaf9795d2a",
    "eventDate": 1579824000000,
    "eventType": "Case Details",
    "formSubmissionId": "0e-6-76b4",
    "providerId": "nifi-user",
    "duration": 0,
    "obs": [],
    "entityType": "Case Details",
    "details": {
        "id": "159",
        "age": "13",
        "bfid": "6305010804",
        "flag": "Site",
        "species": "V",
        "surname": "",
        "focus_id": "",
        "first_name": "",
        "focus_name": "แม่หิต (6305010804)",
        "case_number": "191316000004593200125140915723",
        "family_name": "",
        "focus_reason": "Investigation",
        "focus_status": "A1",
        "house_number": "",
        "ep1_create_date": "2020-01-25T00:00:00.000+0000",
        "ep3_create_date": "2020-01-25T00:00:00.000+0000",
        "investigtion_date": "2020-01-24T00:00:00.000+0000",
        "case_classification": "A"
    },
    "version": 1557860282617,
    "teamId": " ",
    "_id": "",
    "_rev": "v1"
}
```

**Comment by craigappl** [comment]
@Wambere has done a lot of work on generating these events. Can you sit with her to map these out?

**Comment by Wambere** [comment]
The mapping is below

| Item | Source |
| ----- | --------- |
| Case Classification | event.details.case_classification |
| Species | event.details.species |
| Investigation Date | event.details.investigtion_date |
| House Number | event.details.house_number |
| Patient Name | event.details.first_name |
| Surname | event.details.surname |
| Age | event.details.age |
| Notification Date | event.details.ep1_create_date |
| Date of Diagnosis | event.details.ep3_create_date |


Foci Information
The flag (event.details.flag) will show if it is "Site" for foci of residence or "Source" for foci of infection. You can only have one per event

| Item | Source |
| ----- | --------- |
| ID | event.details.focus_id |
| Classification | event.details.focus_status |
| Name | event.details.focus_name |
