### ISSUE TITLE
Data Submitted on Reveal-stage Plans not Showing on Dashboards

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#741]
- [ ] Data submitted against plans on reveal-stage are not showing on the dashboard. A check by @craigappl showed that it looked like there's a table that is missing on stage, which is the reason dashboards aren't working. It's called "temp.zambia_irs_jurisdictions". @moshthepitt would you have additional information on this?

**Comment by moshthepitt** [comment]
@samkanga @craigappl 

1. Reveal stage is configured to work with Namibia-style IRS tables, which is why something like `public.namibia_irs_jurisdictions` exists while the equivalent Zambia table does not.  Please do note that the web UI can currently only work with one IRS configuration at a time.
2. There is no `temp` schema on the Reveal stage database.  We only have `public` as seen here https://superset.reveal-stage.smartregister.org/superset/sqllab - which means that the table would be known as `public.zambia_irs_jurisdictions` instead of temp.zambia_irs_jurisdictions

**Comment by moshthepitt** [comment]
@samkanga @craigappl closing this as it was fixed.  Please reopen if it is still an issue.
