### ISSUE TITLE
One cannot create new plans

### ISSUE THREAD

**Issue by Naima-Bashir** [onaio/reveal-frontend#853]
Login to the system
Click on manage plans
Click on add new plan
Try to select a focus area from the options.
RESULTS: There are no options to select from 
![image](https://user-images.githubusercontent.com/61143692/81586471-3c1fae80-93be-11ea-9fff-ba3ad6b78fea.png)

**Comment by p-netm** [comment]
@Naima-Bashir closing this because its a symptom of an existing issue #782. Essentially we do not have a graceful way to deal with expiration of session token, The web app continues trying to use the expired token that results in failed GET requests that results in the above issue.

Please feel free to reopen this if there is anything that needs re-considering

**Comment by Naima-Bashir** [comment]
sure @p-netm
