### ISSUE TITLE
RVL- 989 - Development of the CSV Upload feature on WebUI

### ISSUE THREAD

**Issue by samkanga** [onaio/reveal-frontend#959]
- [x] A user will go to the admin menu on the reveal webUI and have an option to select **Jurisdiction IRS Risk and Target** option. This will load a page that has an option to download the csv file template. See screenshot below.
![image](https://user-images.githubusercontent.com/5908630/85689595-6feb3500-b6db-11ea-9363-2bb4e001017a.png)

- [x] Once the user fill in the data for risk data and targets, they should have an option to upload the csv file. See screeshot  below showing a sample uploaded csv file.
![image](https://user-images.githubusercontent.com/5908630/85690365-2cdd9180-b6dc-11ea-9b0e-832eaba6cb07.png)

**Comment by moshthepitt** [comment]
Some notes:

- This page will be title "Jusridiction Metadata" and not mention "risk and target" specifically.  Although I am open to having the label being a configurable thing if we really want it
- The download CSV template may not have a "last updated date".  It would merely be downloading a CSV file with the "jurisdiction_id" and "jurisdiction_name" filled out
- The <description> goes here text will be left out until it is provided

**Comment by samkanga** [comment]
@gmwasi @moshthepitt Find below text to include on the <description goes here> section:

**Comment by gmwasi** [comment]
@samkanga @moshthepitt I have added a forth step which is to select the file saved so that the whole description reads:

1. Click on the download template CSV button below.
2. Open the downloaded file and complete the risk and target details on the respective columns.
3. Save the updated CSV file
4. Select the saved file on the upload form
5. Click the "Upload new CSV" button to complete the process
